In [189]:
import torch
from torch import nn, Tensor
from torch.nn import TransformerEncoder, TransformerEncoderLayer
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader, dataset
import numpy as np
from matplotlib import pyplot
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk import word_tokenize
import nltk
from data_loading_code import preprocess_pandas
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, classification_report

import math
import os
from tempfile import TemporaryDirectory
from typing import Tuple

import time


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("device is", device)

device is cpu


In [190]:
class TransformerModel(nn.Module):

    def __init__(self, ntoken: int, d_model: int, nhead: int, d_hid: int,
                 nlayers: int, dropout: float = 0.5):
        super().__init__()
        self.model_type = 'Transformer'
        self.pos_encoder = PositionalEncoding(d_model, dropout)
        encoder_layers = TransformerEncoderLayer(d_model, nhead, d_hid, dropout)
        self.transformer_encoder = TransformerEncoder(encoder_layers, nlayers)
        self.embedding = nn.Embedding(ntoken, d_model)
        self.d_model = d_model
        self.linear = nn.Linear(d_model, ntoken)

        self.init_weights()

    def init_weights(self) -> None:
        initrange = 0.1
        self.embedding.weight.data.uniform_(-initrange, initrange)
        self.linear.bias.data.zero_()
        self.linear.weight.data.uniform_(-initrange, initrange)

    def forward(self, src: Tensor, src_mask: Tensor = None) -> Tensor:
        """
        Arguments:
            src: Tensor, shape ``[seq_len, batch_size]``
            src_mask: Tensor, shape ``[seq_len, seq_len]``

        Returns:
            output Tensor of shape ``[seq_len, batch_size, ntoken]``
        """
        src = self.embedding(src) * math.sqrt(self.d_model)
        src = self.pos_encoder(src)
        if src_mask is None:
            """Generate a square causal mask for the sequence. The masked positions are filled with float('-inf').
            Unmasked positions are filled with float(0.0).
            """
            src_mask = nn.Transformer.generate_square_subsequent_mask(len(src)).to(device)
        output = self.transformer_encoder(src, src_mask)
        output = self.linear(output)
        return output

class PositionalEncoding(nn.Module):

    def __init__(self, d_model: int, dropout: float = 0.1, max_len: int = 5000):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        position = torch.arange(max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
        pe = torch.zeros(max_len, 1, d_model)
        pe[:, 0, 0::2] = torch.sin(position * div_term)
        pe[:, 0, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe)

    def forward(self, x: Tensor) -> Tensor:
        """
        Arguments:
            x: Tensor, shape ``[seq_len, batch_size, embedding_dim]``
        """
        x = x + self.pe[:x.size(0)]
        return self.dropout(x)

In [191]:
from torchtext.datasets import WikiText2
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator       
import copy     # pre-process

data = pd.read_csv("amazon_cells_labelled.txt", delimiter='\t', header=None)
data.columns = ['Sentence', 'Class']
data['index'] = data.index                                          # add new column index
columns = ['index', 'Class', 'Sentence']
data = preprocess_pandas(data, columns)   

train_iter, val_iter, test_iter = \
              np.split(data.sample(frac=1, random_state=42), 
                       [int(.6*len(data)), int(.8*len(data))])

train_iter2 = copy.deepcopy(train_iter)

tokenizer = get_tokenizer('basic_english')
vocab = build_vocab_from_iterator(map(tokenizer, train_iter2["Sentence"]), specials=['<unk>'])
vocab.set_default_index(vocab['<unk>'])

#nltk.download('punkt')
#nltk.download('stopwords')
# get data, pre-process and split              

def data_process(raw_text_iter: dataset.IterableDataset) -> Tensor:
    """Converts raw text into a flat Tensor."""
    data2 = [torch.tensor(vocab(tokenizer(item)), dtype=torch.long) for item in raw_text_iter]
    print(data2)
    return torch.cat(tuple(filter(lambda t: t.numel() > 0, data2)))


train_data = data_process(train_iter["Sentence"])
val_data = data_process(val_iter["Sentence"])
test_data = data_process(test_iter["Sentence"])


def batchify(data: Tensor, bsz: int) -> Tensor:
    """Divides the data into ``bsz`` separate sequences, removing extra elements
    that wouldn't cleanly fit.

    Arguments:
        data: Tensor, shape ``[N]``
        bsz: int, batch size

    Returns:
        Tensor of shape ``[N // bsz, bsz]``
    """
    seq_len = data.size(0) // bsz
    data = data[:seq_len * bsz]
    data = data.view(bsz, seq_len).t().contiguous()
    return data.to(device)

batch_size = 20
eval_batch_size = 10
train_data = batchify(train_data, batch_size)  # shape ``[seq_len, batch_size]``
val_data = batchify(val_data, eval_batch_size)
test_data = batchify(test_data, eval_batch_size)

#training_data, validation_data, training_labels, validation_labels = train_test_split( # split the data into training, validation, and test splits
#    data['Sentence'].values.astype('U'),
#    data['Class'].values.astype('int32'),
#    test_size=0.10,
#    random_state=0,
#    shuffle=True
#)
#
## vectorize data using TFIDF and transform for PyTorch for scalability
#word_vectorizer = TfidfVectorizer(analyzer='word', ngram_range=(1,2), max_features=50000, max_df=0.5, use_idf=True, norm='l2')
#training_data = word_vectorizer.fit_transform(training_data)        # transform texts to sparse matrix
#training_data = training_data.todense()                             # convert to dense matrix for Pytorch
#vocab_size = len(word_vectorizer.vocabulary_)
#validation_data = word_vectorizer.transform(validation_data)
#validation_data = validation_data.todense()
#
#train_x_tensor = torch.from_numpy(np.array(training_data)).type(torch.FloatTensor)
#train_y_tensor = torch.from_numpy(np.array(training_labels)).long()
#validation_x_tensor = torch.from_numpy(np.array(validation_data)).type(torch.FloatTensor)
#validation_y_tensor = torch.from_numpy(np.array(validation_labels)).long()
#
#class TransfromerDataset(torch.utils.data.Dataset):
#    def __init__(self, datasetA, bptt):
#        self.source = datasetA
#        self.bptt = bptt
#
#    def __getitem__(self, i):
#        seq_len = min(self.bptt, len(self.source) - 1 - i)
#        data = self.source[i:i+seq_len]
#        target = self.source[i+1:i+1+seq_len].reshape(-1)
#        return data, target
#
#    def __len__(self):
#        return min(len(self.datasetA))
#    
#train_ds = ConcatDataset(train_x_tensor,train_y_tensor)
#val_ds = ConcatDataset(validation_x_tensor,validation_y_tensor)
#train_loader = DataLoader(train_ds,batch_size=5)
#val_loader = DataLoader(val_ds,batch_size=5)

[tensor([1280,  194,    9,  167,   16,  243,    2,  551,    3,  254,   16,   10,
          26,   68,   12]), tensor([   2, 1303,    7,  566,  435,    4,  182,    5,  106, 1295,    6,  419,
           1]), tensor([  3,  61, 140,  48,   8,  29,   1]), tensor([   8,   59,   18,  121,    2,  333, 1315,  412,    4,    5,  170,    2,
         120,   89,    3,  187,    9,  126,    5,   24,    1]), tensor([  3, 140,  48,   8, 117,   9, 816,  12]), tensor([   5,   30,  119,   21,   14,  124,  674,    6,    4,   10,  209,   51,
          47,    2, 1365,   31,  138,    1]), tensor([  73,   11,   25,  123,    2,  162,  327,   22,    3,  138,    4, 1102,
          73,   11,   25,   72,    8,   13,    1]), tensor([   3,   92,    2,  606,   49,   16,   14,   94,  333, 1335,    4,    5,
          78,   60, 1346,   46, 1127,   14,  892,  257,   38,  155,    1]), tensor([147,  29,   6,   4, 130,  15,  93,  12]), tensor([ 23,  26, 542,  16,   2,  68,   1]), tensor([365,   5,  30,  62, 365,   5,   7, 104,

C:\Users\Anton\AppData\Roaming\Python\Python312\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


In [192]:
bptt = 35
def get_batch(source: Tensor, i: int) -> Tuple[Tensor, Tensor]:
    """
    Args:
        source: Tensor, shape ``[full_seq_len, batch_size]``
        i: int

    Returns:
        tuple (data, target), where data has shape ``[seq_len, batch_size]`` and
        target has shape ``[seq_len * batch_size]``
    """
    seq_len = min(bptt, len(source) - 1 - i)
    data = source[i:i+seq_len]
    target = source[i+1:i+1+seq_len].reshape(-1)
    return data, target


In [226]:
ntokens = len(vocab)  # size of vocabulary
emsize = 200  # embedding dimension
d_hid = 200  # dimension of the feedforward network model in ``nn.TransformerEncoder``
nlayers = 2  # number of ``nn.TransformerEncoderLayer`` in ``nn.TransformerEncoder``
nhead = 2  # number of heads in ``nn.MultiheadAttention``
dropout = 0.45  # dropout probability
model = TransformerModel(ntokens, emsize, nhead, d_hid, nlayers, dropout).to(device)

In [230]:
criterion = nn.CrossEntropyLoss()
lr = 30.0  # learning rate
optimizer = torch.optim.SGD(model.parameters(), lr=lr)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 3.0, gamma=0.95)

def train(model: nn.Module) -> None:
    model.train()  # turn on train mode
    total_loss = 0.
    log_interval = 2
    start_time = time.time()

    num_batches = len(train_data) // bptt
    for batch, i in enumerate(range(0, train_data.size(0) - 1, bptt)):
        data, targets = get_batch(train_data, i)
        output = model(data)
        output_flat = output.view(-1, ntokens)
        loss = criterion(output_flat, targets)

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.5)
        optimizer.step()

        total_loss += loss.item()
        if batch % log_interval == 0 and batch > 0:
            lr = scheduler.get_last_lr()[0]
            ms_per_batch = (time.time() - start_time) * 1000 / log_interval
            cur_loss = total_loss / log_interval
            ppl = math.exp(cur_loss)
            print(f'| epoch {epoch:3d} | {batch:5d}/{num_batches:5d} batches | '
                  f'lr {lr:02.2f} | ms/batch {ms_per_batch:5.2f} | '
                  f'loss {cur_loss:5.2f} | ppl {ppl:8.2f}')
            total_loss = 0
            start_time = time.time()

def evaluate(model: nn.Module, eval_data: Tensor) -> float:
    model.eval()  # turn on evaluation mode
    total_loss = 0.
    with torch.no_grad():
        for i in range(0, eval_data.size(0) - 1, bptt):
            data, targets = get_batch(eval_data, i)
            seq_len = data.size(0)
            output = model(data)
            output_flat = output.view(-1, ntokens)
            total_loss += seq_len * criterion(output_flat, targets).item()
    return total_loss / (len(eval_data) - 1)

In [231]:
best_val_loss = float('inf')
epochs = 500

with TemporaryDirectory() as tempdir:
    best_model_params_path = os.path.join(tempdir, "best_model_params.pt")

    for epoch in range(1, epochs + 1):
        epoch_start_time = time.time()
        train(model)
        val_loss = evaluate(model, val_data)
        val_ppl = math.exp(val_loss)
        elapsed = time.time() - epoch_start_time
        print('-' * 89)
        print(f'| end of epoch {epoch:3d} | time: {elapsed:5.2f}s | '
            f'valid loss {val_loss:5.2f} | valid ppl {val_ppl:8.2f}')
        print('-' * 89)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), best_model_params_path)

        scheduler.step()
    model.load_state_dict(torch.load(best_model_params_path)) # load best model states

| epoch   1 |     2/   10 batches | lr 30.00 | ms/batch 152.95 | loss 18.82 | ppl 148837131.62
| epoch   1 |     4/   10 batches | lr 30.00 | ms/batch 58.23 | loss 13.66 | ppl 857966.33
| epoch   1 |     6/   10 batches | lr 30.00 | ms/batch 54.35 | loss 33.18 | ppl 257650664703349.38
| epoch   1 |     8/   10 batches | lr 30.00 | ms/batch 78.05 | loss 39.33 | ppl 120995284583087152.00
| epoch   1 |    10/   10 batches | lr 30.00 | ms/batch 50.38 | loss 75.33 | ppl 518211706981793670724880531718144.00
-----------------------------------------------------------------------------------------
| end of epoch   1 | time:  0.88s | valid loss 59.21 | valid ppl 51744103059810939637334016.00
-----------------------------------------------------------------------------------------
| epoch   2 |     2/   10 batches | lr 30.00 | ms/batch 220.30 | loss 109.15 | ppl 253467208510786375748155564915608304138623909888.00
| epoch   2 |     4/   10 batches | lr 30.00 | ms/batch 54.89 | loss 29.64 | ppl 74

KeyboardInterrupt: 

In [232]:
inp = "I like this phone"
tokens = tokenizer(inp)
embed = torch.tensor([vocab(tokens)], dtype=torch.long)
print(inp)
print(tokens)
print(embed)
print(embed.shape)
print(embed.dtype)
print(type(embed))
output = model(embed)
print(output.shape)
output_flat = output.view(-1, ntokens)
print(output_flat.shape)
print(output_flat)


I like this phone
['i', 'like', 'this', 'phone']
tensor([[ 3, 56,  8, 13]])
torch.Size([1, 4])
torch.int64
<class 'torch.Tensor'>
torch.Size([1, 4, 1370])
torch.Size([4, 1370])
tensor([[-1.7706,  5.8401,  5.1357,  ..., -0.6910, -0.6759, -0.6924],
        [-1.7783,  5.8188,  5.1298,  ..., -0.6968, -0.6570, -0.6561],
        [-1.7639,  5.8071,  5.1173,  ..., -0.6922, -0.6557, -0.6722],
        [-1.7778,  5.8450,  5.1359,  ..., -0.6988, -0.6747, -0.6756]],
       grad_fn=<ViewBackward0>)


In [233]:
class FFF(nn.Module):
    def __init__(self,vocab_sz):
        super().__init__()
        self.linear1=nn.Linear(vocab_sz,100)
        self.linear2=nn.Linear(100,10)
        self.linear3=nn.Linear(10,2)
        self.sm = nn.Softmax()
    
    def forward(self,x):
        x = self.linear1(x)
        x = self.linear2(x)
        x = self.linear3(x)
        x = self.sm(x)
        return x

In [234]:
torch.Size([1, 4, 1370])

torch.Size([1, 4, 1370])

In [235]:
x = torch.rand((4,8))
print(x)
x = x[0,:]
print(x)


tensor([[0.4485, 0.0504, 0.9616, 0.9986, 0.1029, 0.8820, 0.9473, 0.5201],
        [0.4741, 0.2143, 0.6585, 0.6786, 0.6870, 0.8034, 0.9179, 0.7555],
        [0.5861, 0.4257, 0.4761, 0.5964, 0.7848, 0.9654, 0.9058, 0.8898],
        [0.8389, 0.8983, 0.1311, 0.3281, 0.8423, 0.9665, 0.7154, 0.9933]])
tensor([0.4485, 0.0504, 0.9616, 0.9986, 0.1029, 0.8820, 0.9473, 0.5201])


In [236]:
data = pd.read_csv("amazon_cells_labelled.txt", delimiter='\t', header=None)
data.columns = ['Sentence', 'Class']
data['index'] = data.index                                          # add new column index
columns = ['index', 'Class', 'Sentence']
data = preprocess_pandas(data, columns)                             # pre-process
training_data, validation_data, training_labels, validation_labels = train_test_split( # split the data into training, validation, and test splits
    data['Sentence'].values.astype('U'),
    data['Class'].values.astype('int32'),
    test_size=0.10,
    random_state=0,
    shuffle=True
)

print(training_data)
print(type(training_data[0]))

# vectorize data using TFIDF and transform for PyTorch for scalability
#word_vectorizer = TfidfVectorizer(analyzer='word', ngram_range=(1,2), max_features=50000, max_df=0.5, use_idf=True, norm='l2')
#training_data = word_vectorizer.fit_transform(training_data)        # transform texts to sparse matrix
#training_data = training_data.todense()                             # convert to dense matrix for Pytorch
#vocab_size = len(word_vectorizer.vocabulary_)
#validation_data = word_vectorizer.transform(validation_data)
#validation_data = validation_data.todense()

#train_x_tensor = torch.from_numpy(np.array(training_data)).type(torch.FloatTensor)
train_y_tensor = torch.from_numpy(np.array(training_labels)).long()
#validation_x_tensor = torch.from_numpy(np.array(validation_data)).type(torch.FloatTensor)
validation_y_tensor = torch.from_numpy(np.array(validation_labels)).long()

['this allows the possibility of double booking for the same date and time after the first.'
 'my sister has one also and she loves it.'
 "the one big drawback of the mp player is that the buttons on the phone's front cover that let you pause and skip songs lock out after a few seconds."
 'the cutouts and buttons are placed perfectly.'
 'this is definitely a must have if your state does not allow cell phone usage while driving.'
 'these are fabulous!' 'nice sound.'
 "i can't use this case because the smell is disgusting."
 'i really like this product over the motorola because it is allot clearer on the ear piece and the mic.'
 'fast service.' 'i found this product to be waaay too big.'
 "it plays louder than any other speaker of this size; the price is so low that most would think the quality is lacking, however, it's not."
 'no buyers remorse on this one!.'
 'i had to go to a store and bought a new nokia phone which is working great.'
 'poor quality and service.'
 'the worst piece of 

In [237]:
class ConcatDataset(torch.utils.data.Dataset):
    def __init__(self, datasetA, datasetB):
        self.datasetA = datasetA
        self.datasetB = datasetB

    def __getitem__(self, i):
        inp = self.datasetA[i]
        tokens = tokenizer(inp)
        embed = torch.tensor(vocab(tokens), dtype=torch.long)
        label = F.one_hot(self.datasetB[i],num_classes=2)
        output = model(embed)
        output_flat = output.view(-1, ntokens)[0,:]
        return output_flat,label

    def __len__(self):
        return min(len(self.datasetA),len(self.datasetB))

In [238]:
train_ds = ConcatDataset(training_data,train_y_tensor)
val_ds = ConcatDataset(validation_data,validation_y_tensor)
print(len(training_data),len(train_y_tensor))
train_loader = DataLoader(train_ds,batch_size=16)
val_loader = DataLoader(val_ds,batch_size=16)

900 900


In [203]:
it = iter(train_loader)

In [204]:
next(it)

[tensor([[ 0.5078,  4.3731,  2.8611,  ..., -0.8538,  0.4049, -0.1154],
         [ 0.1376,  2.7581,  2.8332,  ..., -0.1256, -0.3346, -0.9207],
         [-0.7646,  4.1434,  0.2521,  ..., -0.7375,  0.1870,  0.0129],
         [-0.7646,  4.1434,  0.2521,  ..., -0.7375,  0.1870,  0.0129],
         [ 0.5078,  4.3731,  2.8611,  ..., -0.8538,  0.4049, -0.1154]],
        grad_fn=<StackBackward0>),
 tensor([[1, 0],
         [0, 1],
         [1, 0],
         [0, 1],
         [0, 1]])]

In [239]:
def train_model(model, criterion, optimizer, train_loader, val_loader, num_epochs):
    best_val_loss = float('inf')
    best_model = model

    for epoch in range(num_epochs):
        print(f"Starting epoch {epoch+1} of {num_epochs}")
        model.train()
        train_loss = 0.0
        for batch_nr, (inputs, labels) in enumerate(train_loader):
            inputs = inputs.to(device)
            labels = labels.to(device).to(torch.float)
            
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss = loss.to(device)

            if (batch_nr%80 == 0):
                print(f"Processing batch number {batch_nr+1} of {len(train_loader)}")
                print(outputs)
                print(labels)
                print("current loss",loss.item())
                
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * inputs.size(0)
        
        train_loss /= len(train_loader.dataset)
    
    # Validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs = inputs.to(device)
            labels = labels.to(device).to(torch.float)
            outputs = model(inputs)
        
            loss = criterion(outputs, labels)
            val_loss += loss.item() * inputs.size(0)
    
    val_loss /= len(val_loader.dataset)
    
    if (epoch + 1) % 10 == 0:
        print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}')
    
    # Save the best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model = model
    return best_model

In [240]:
LEARNING_RATE = 0.0001
EPOCHS = 10

model2 = FFF(len(vocab))

print(device)
criterion = torch.nn.CrossEntropyLoss().to(device)
# optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

optimizer = torch.optim.Adam(model2.parameters(), lr=LEARNING_RATE)

# Train the model
trained_model = train_model(model2, criterion, optimizer, train_loader, val_loader, EPOCHS)

cpu
Starting epoch 1 of 10


C:\Users\Anton\AppData\Roaming\Python\Python312\site-packages\torch\nn\modules\module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


Processing batch number 1 of 57
tensor([[0.5394, 0.4606],
        [0.5378, 0.4622],
        [0.5383, 0.4617],
        [0.5376, 0.4624],
        [0.5400, 0.4600],
        [0.5383, 0.4617],
        [0.5399, 0.4601],
        [0.5405, 0.4595],
        [0.5412, 0.4588],
        [0.5389, 0.4611],
        [0.5403, 0.4597],
        [0.5392, 0.4608],
        [0.5395, 0.4605],
        [0.5392, 0.4608],
        [0.5405, 0.4595],
        [0.5401, 0.4599]], grad_fn=<SoftmaxBackward0>)
tensor([[1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.]])
current loss 0.6985097527503967
Starting epoch 2 of 10
Processing batch number 1 of 57
tensor([[0.5948, 0.4052],
        [0.5938, 0.4062],
        [0.5963, 0.4037],
        [0.5944, 0.4056],
        [0.5949, 0.4051],
        [0.5963, 

KeyboardInterrupt: 

In [215]:
while True:
    inp = input("Leave a review:")
    if inp=="exit":
        break
    tokens = tokenizer(inp)
    embed = torch.tensor(vocab(tokens), dtype=torch.long)
    output = model(embed)
    output_flat = output.view(-1, ntokens)[0,:]
    pred = model2(output_flat).tolist()
    print(pred)
    if(pred[0]>0.5):
        print("You seem to dislike this thing")
    else:
        print("You seem to like this thing")

torch.Size([1370])
[0.46550995111465454, 0.5344901084899902]
You seem to like this thing
torch.Size([1370])
[0.46550995111465454, 0.5344901084899902]
You seem to like this thing
torch.Size([1370])
[0.46550995111465454, 0.5344901084899902]
You seem to like this thing
torch.Size([1370])
[0.9517692923545837, 0.04823073372244835]
You seem to dislike this thing
torch.Size([1370])
[0.5945248007774353, 0.4054751396179199]
You seem to dislike this thing
torch.Size([1370])
[0.9309284090995789, 0.06907162070274353]
You seem to dislike this thing
torch.Size([1370])
[0.46550995111465454, 0.5344901084899902]
You seem to like this thing
